version: '3'
services:
  db:
    image: 'postgres:13.2-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=spotify
      - POSTGRES_DB=spotify
    volumes:
      - db-data:/var/lib/postgresql/data # persist data even if container shuts down
  app: 
    build: ./docker/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/opt/cs6242_home
    depends_on:
      - db
  web-app:
    build: ./web-app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web-app:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  db-data: # names volumes can be managed easier using docker-compose
