version: '3'
services:
  data_collection: 
    build: ./docker/data_collection
    ports:
      - "8888:8888"
      - "6006:6006"
      - "8000:8000"
    volumes:
      - .:/opt/cs6242_home/
      - /media/djbiega/My Passport/CS6242_Spotify_Dataset/:/opt/data/
    networks:
      - my_network
    depends_on:
      - db
  db:
    image: 'postgres:13.2-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=spotify
      - POSTGRES_DB=spotify
    volumes:
      - db-data:/var/lib/postgresql/data # persist data even if container shuts down
    networks:
      - my_network

volumes:
  db-data: # names volumes can be managed easier using docker-compose

networks:
  my_network:
